export interface SurahPageMapping {
  number: number;
  englishName: string;
  name: string;
  startPage: number;
}

export interface ParahMapping {
  number: number;
  englishName: string;
  arabicName: string;
  startPage: number;
  surahStart: string;
}

export const SURA_START_PAGES: SurahPageMapping[] = [
  { number: 1, englishName: "Al-Fatiha", name: "الفاتحة", startPage: 1 },
  { number: 2, englishName: "Al-Baqara", name: "البقرة", startPage: 2 },
  { number: 3, englishName: "Aal-i-Imraan", name: "آل عمران", startPage: 50 },
  { number: 4, englishName: "An-Nisaa", name: "النساء", startPage: 77 },
  { number: 5, englishName: "Al-Maaida", name: "المائدة", startPage: 106 },
  { number: 6, englishName: "Al-An'aam", name: "الأنعام", startPage: 128 },
  { number: 7, englishName: "Al-A'raaf", name: "الأعراف", startPage: 151 },
  { number: 8, englishName: "Al-Anfaal", name: "الأنفال", startPage: 177 },
  { number: 9, englishName: "At-Tawba", name: "التوبة", startPage: 187 },
  { number: 10, englishName: "Yunus", name: "يونس", startPage: 208 },
  { number: 11, englishName: "Hud", name: "هود", startPage: 221 },
  { number: 12, englishName: "Yusuf", name: "يوسف", startPage: 235 },
  { number: 13, englishName: "Ar-Ra'd", name: "الرعد", startPage: 249 },
  { number: 14, englishName: "Ibrahim", name: "إبراهيم", startPage: 255 },
  { number: 15, englishName: "Al-Hijr", name: "الحجر", startPage: 262 },
  { number: 16, englishName: "An-Nahl", name: "النحل", startPage: 267 },
  { number: 17, englishName: "Al-Israa", name: "الإسراء", startPage: 282 },
  { number: 18, englishName: "Al-Kahf", name: "الكهف", startPage: 293 },
  { number: 19, englishName: "Maryam", name: "مريم", startPage: 305 },
  { number: 20, englishName: "Ta-Ha", name: "طه", startPage: 312 },
  { number: 21, englishName: "Al-Anbiyaa", name: "الأنبياء", startPage: 322 },
  { number: 22, englishName: "Al-Hajj", name: "الحج", startPage: 332 },
  { number: 23, englishName: "Al-Mu'minoon", name: "المؤمنون", startPage: 342 },
  { number: 24, englishName: "An-Noor", name: "النور", startPage: 350 },
  { number: 25, englishName: "Al-Furqaan", name: "الفرقان", startPage: 359 },
  { number: 26, englishName: "Ash-Shu'araa", name: "الشعراء", startPage: 367 },
  { number: 27, englishName: "An-Naml", name: "النمل", startPage: 377 },
  { number: 28, englishName: "Al-Qasas", name: "القصص", startPage: 385 },
  { number: 29, englishName: "Al-Ankaboot", name: "العنكبوت", startPage: 396 },
  { number: 30, englishName: "Ar-Rum", name: "الروم", startPage: 404 },
  { number: 31, englishName: "Luqman", name: "لقمان", startPage: 411 },
  { number: 32, englishName: "As-Sajda", name: "السجدة", startPage: 415 },
  { number: 33, englishName: "Al-Ahzaab", name: "الأحزاب", startPage: 418 },
  { number: 34, englishName: "Saba", name: "سبأ", startPage: 428 },
  { number: 35, englishName: "Fatir", name: "فاطر", startPage: 434 },
  { number: 36, englishName: "Ya-Seen", name: "يس", startPage: 440 },
  { number: 37, englishName: "As-Saaffat", name: "الصافات", startPage: 446 },
  { number: 38, englishName: "Sad", name: "ص", startPage: 453 },
  { number: 39, englishName: "Az-Zumar", name: "الزمر", startPage: 458 },
  { number: 40, englishName: "Ghafir", name: "غافر", startPage: 467 },
  { number: 41, englishName: "Fussilat", name: "فصلت", startPage: 477 },
  { number: 42, englishName: "Ash-Shura", name: "الشورى", startPage: 483 },
  { number: 43, englishName: "Az-Zukhruf", name: "الزخرف", startPage: 489 },
  { number: 44, englishName: "Ad-Dukhan", name: "الدخان", startPage: 496 },
  { number: 45, englishName: "Al-Jathiya", name: "الجاثية", startPage: 499 },
  { number: 46, englishName: "Al-Ahqaf", name: "الأحقاف", startPage: 502 },
  { number: 47, englishName: "Muhammad", name: "محمد", startPage: 507 },
  { number: 48, englishName: "Al-Fath", name: "الفتح", startPage: 511 },
  { number: 49, englishName: "Al-Hujraat", name: "الحجرات", startPage: 515 },
  { number: 50, englishName: "Qaf", name: "ق", startPage: 518 },
  { number: 51, englishName: "Adh-Dhariyat", name: "الذاريات", startPage: 520 },
  { number: 52, englishName: "At-Tur", name: "الطور", startPage: 523 },
  { number: 53, englishName: "An-Najm", name: "النجم", startPage: 526 },
  { number: 54, englishName: "Al-Qamar", name: "القمر", startPage: 528 },
  { number: 55, englishName: "Ar-Rahman", name: "الرحمن", startPage: 531 },
  { number: 56, englishName: "Al-Waqia", name: "الواقعة", startPage: 534 },
  { number: 57, englishName: "Al-Hadid", name: "الحديد", startPage: 537 },
  { number: 58, englishName: "Al-Mujadila", name: "المجادلة", startPage: 542 },
  { number: 59, englishName: "Al-Hashr", name: "الحشر", startPage: 545 },
  { number: 60, englishName: "Al-Mumtahina", name: "الممتحنة", startPage: 549 },
  { number: 61, englishName: "As-Saff", name: "الصف", startPage: 551 },
  { number: 62, englishName: "Al-Jumua", name: "الجمعة", startPage: 553 },
  { number: 63, englishName: "Al-Munafiqoon", name: "المنافقون", startPage: 554 },
  { number: 64, englishName: "At-Taghabun", name: "التغابن", startPage: 556 },
  { number: 65, englishName: "At-Talaq", name: "الطلاق", startPage: 558 },
  { number: 66, englishName: "At-Tahrim", name: "التحريم", startPage: 560 },
  { number: 67, englishName: "Al-Mulk", name: "الملك", startPage: 562 },
  { number: 68, englishName: "Al-Qalam", name: "القلم", startPage: 564 },
  { number: 69, englishName: "Al-Haaqqa", name: "الحاقة", startPage: 566 },
  { number: 70, englishName: "Al-Maarij", name: "المعارج", startPage: 568 },
  { number: 71, englishName: "Nooh", name: "نوح", startPage: 570 },
  { number: 72, englishName: "Al-Jinn", name: "الجن", startPage: 572 },
  { number: 73, englishName: "Al-Muzzammil", name: "المزمل", startPage: 574 },
  { number: 74, englishName: "Al-Muddaththir", name: "المدثر", startPage: 575 },
  { number: 75, englishName: "Al-Qiyama", name: "القيامة", startPage: 577 },
  { number: 76, englishName: "Al-Insan", name: "الإنسان", startPage: 578 },
  { number: 77, englishName: "Al-Mursalat", name: "المرسلات", startPage: 580 },
  { number: 78, englishName: "An-Naba", name: "النبأ", startPage: 582 },
  { number: 79, englishName: "An-Naziat", name: "النازعات", startPage: 583 },
  { number: 80, englishName: "Abasa", name: "عبس", startPage: 585 },
  { number: 81, englishName: "At-Takwir", name: "التكوير", startPage: 586 },
  { number: 82, englishName: "Al-Infitar", name: "الانفطار", startPage: 587 },
  { number: 83, englishName: "Al-Mutaffifin", name: "المطففين", startPage: 587 },
  { number: 84, englishName: "Al-Inshiqaq", name: "الانشقاق", startPage: 589 },
  { number: 85, englishName: "Al-Burooj", name: "البروج", startPage: 590 },
  { number: 86, englishName: "At-Tariq", name: "الطارق", startPage: 591 },
  { number: 87, englishName: "Al-Ala", name: "الأعلى", startPage: 591 },
  { number: 88, englishName: "Al-Ghashiya", name: "الغاشية", startPage: 592 },
  { number: 89, englishName: "Al-Fajr", name: "الفجر", startPage: 593 },
  { number: 90, englishName: "Al-Balad", name: "البلد", startPage: 594 },
  { number: 91, englishName: "Ash-Shams", name: "الشمس", startPage: 595 },
  { number: 92, englishName: "Al-Lail", name: "الليل", startPage: 595 },
  { number: 93, englishName: "Ad-Dhuha", name: "الضحى", startPage: 596 },
  { number: 94, englishName: "Al-Inshirah", name: "الشرح", startPage: 596 },
  { number: 95, englishName: "At-Tin", name: "التين", startPage: 597 },
  { number: 96, englishName: "Al-Alaq", name: "العلق", startPage: 597 },
  { number: 97, englishName: "Al-Qadr", name: "القدر", startPage: 598 },
  { number: 98, englishName: "Al-Bayyina", name: "البينة", startPage: 598 },
  { number: 99, englishName: "Az-Zalzala", name: "الزلزلة", startPage: 599 },
  { number: 100, englishName: "Al-Adiyat", name: "العاديات", startPage: 599 },
  { number: 101, englishName: "Al-Qaria", name: "القارعة", startPage: 600 },
  { number: 102, englishName: "At-Takathur", name: "التكاثر", startPage: 600 },
  { number: 103, englishName: "Al-Asr", name: "العصر", startPage: 601 },
  { number: 104, englishName: "Al-Humaza", name: "الهمزة", startPage: 601 },
  { number: 105, englishName: "Al-Fil", name: "الفيل", startPage: 601 },
  { number: 106, englishName: "Quraish", name: "قريش", startPage: 602 },
  { number: 107, englishName: "Al-Ma'un", name: "الماعون", startPage: 602 },
  { number: 108, englishName: "Al-Kawthar", name: "الكوثر", startPage: 602 },
  { number: 109, englishName: "Al-Kafirun", name: "الكافرون", startPage: 603 },
  { number: 110, englishName: "An-Nasr", name: "النصر", startPage: 603 },
  { number: 111, englishName: "Al-Masad", name: "المسد", startPage: 603 },
  { number: 112, englishName: "Al-Ikhlas", name: "الإخلاص", startPage: 604 },
  { number: 113, englishName: "Al-Falaq", name: "الفلق", startPage: 604 },
  { number: 114, englishName: "An-Nas", name: "الناس", startPage: 604 }
];

export const PARAH_LIST: ParahMapping[] = [
  { number: 1, englishName: "Alif Lam Meem", arabicName: "آلم", startPage: 1, surahStart: "Al-Faatiha:1" },
  { number: 2, englishName: "Sayaqool", arabicName: "سيقول", startPage: 22, surahStart: "Al-Baqara:142" },
  { number: 3, englishName: "Tilkal Rusul", arabicName: "تلك الرسل", startPage: 42, surahStart: "Al-Baqara:253" },
  { number: 4, englishName: "Lan Tanaloo", arabicName: "لن تنالوا", startPage: 62, surahStart: "Aal-i-Imraan:93" },
  { number: 5, englishName: "Wal Muhsanat", arabicName: "والمحصنات", startPage: 82, surahStart: "An-Nisaa:24" },
  { number: 6, englishName: "La Yuhibbullah", arabicName: "لا يحب الله", startPage: 102, surahStart: "An-Nisaa:148" },
  { number: 7, englishName: "Wa Iza Sami'oo", arabicName: "وإذا سمعوا", startPage: 121, surahStart: "Al-Maaida:82" },
  { number: 8, englishName: "Wa Lau Annana", arabicName: "ولو أننا", startPage: 142, surahStart: "Al-An'aam:111" },
  { number: 9, englishName: "Qal Al-Mala'u", arabicName: "قال الملأ", startPage: 162, surahStart: "Al-A'raaf:88" },
  { number: 10, englishName: "Wa'lamoo", arabicName: "واعلموا", startPage: 182, surahStart: "Al-Anfaal:41" },
  { number: 11, englishName: "Ya'taziroon", arabicName: "يعتذرون", startPage: 201, surahStart: "At-Tawba:93" },
  { number: 12, englishName: "Wa Mamin Daabbatin", arabicName: "وما من دابة", startPage: 221, surahStart: "Hud:6" },
  { number: 13, englishName: "Wa Ma Ubabri'oo", arabicName: "وما أبرئ", startPage: 242, surahStart: "Yusuf:53" },
  { number: 14, englishName: "Rubama", arabicName: "ربما", startPage: 262, surahStart: "Al-Hijr:1" },
  { number: 15, englishName: "Subhanallazi", arabicName: "سبحان الذي", startPage: 282, surahStart: "Al-Israa:1" },
  { number: 16, englishName: "Qal Alam", arabicName: "قال ألم", startPage: 302, surahStart: "Al-Kahf:75" },
  { number: 17, englishName: "Aqtaraba", arabicName: "اقترب", startPage: 322, surahStart: "Al-Anbiyaa:1" },
  { number: 18, englishName: "Qad Aflaha", arabicName: "قد أفلح", startPage: 342, surahStart: "Al-Mu'minoon:1" },
  { number: 19, englishName: "Wa Qalallazina", arabicName: "وقال الذين", startPage: 362, surahStart: "Al-Furqaan:21" },
  { number: 20, englishName: "Amman Khalaqa", arabicName: "أمن خلق", startPage: 382, surahStart: "An-Naml:60" },
  { number: 21, englishName: "Utlu Ma Oohiya", arabicName: "اتل ما أوحي", startPage: 402, surahStart: "Al-Ankaboot:45" },
  { number: 22, englishName: "Wa Manyaqnut", arabicName: "ومن يقنت", startPage: 422, surahStart: "Al-Ahzaab:31" },
  { number: 23, englishName: "Wa Mali", arabicName: "وما لي", startPage: 442, surahStart: "Yaseen:22" },
  { number: 24, englishName: "Faman Azlam", arabicName: "فمن أظلم", startPage: 462, surahStart: "Az-Zumar:32" },
  { number: 25, englishName: "Elahe Yuraddu", arabicName: "إليه يرد", startPage: 482, surahStart: "Fussilat:47" },
  { number: 26, englishName: "Ha'a Meem", arabicName: "حم", startPage: 502, surahStart: "Al-Ahqaaf:1" },
  { number: 27, englishName: "Qala Fama Khatbukum", arabicName: "قال فما خطبكم", startPage: 522, surahStart: "Az-Zaariyat:31" },
  { number: 28, englishName: "Qad Sami'allahu", arabicName: "قد سمع الله", startPage: 542, surahStart: "Al-Mujaadila:1" },
  { number: 29, englishName: "Tabarakallazi", arabicName: "تبارك الذي", startPage: 562, surahStart: "Al-Mulk:1" },
  { number: 30, englishName: "Amma Yatasa'aloon", arabicName: "عم يتساءلون", startPage: 582, surahStart: "An-Naba:1" }
];
